name: CI

on:
    pull_request:
        branches: ["main"]
    push:
        branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: download project
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
      - run: npm --prefix To-Do-App/app ci
      - run: npm test
