name: CI

on:
    pull_request:
        branches: ["main", "develop"]
    push:
        branches: ["develop", "main"]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: download project
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
      - run: yarn install
        working-directory: To-Do-App/app
      - run: yarn test
        working-directory: To-Do-App/app


      