name: CI-develop

on:
    pull_request:
        branches: ["develop"]
    push:
        branches: ["develop"]

jobs:
  CI-develop:
    name: CI-develop
    runs-on: ubuntu-latest
    steps:
      - name: download project
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
      - run: yarn install
        working-directory: To-Do-App/app
      - run: yarn test
        working-directory: To-Do-App/app
      