name: CI

on:
    pull_request:
        branches: ["main", "develop"]
    push:
        branches: ["develop", "main"]

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: download project
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
      - run: yarn install
        working-directory: To-Do-App/app
      - run: yarn test
        working-directory: To-Do-App/app
      - name: Log in
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build the docker image
        run: docker build --no-cache -t oswe/to-do-app:1v -f ./To-Do-App/app/Dockerfile .
      - name: Push the Docker image
        run: docker push oswe/to-do-app:1v
      