name: CD-main

on:
    pull_request:
        branches: ["main"]
    push:
        branches: ["main"]

jobs:
  CD-main:
    name: CD-main
    runs-on: self-hosted
    steps:
      - name: download the image
        run: docker pull oswe/to-do-app:latest
      - name: run the container
        run: docker run -d -p 3000:3000 oswe/to-do-app:latest
      